### ISSUE TITLE
A few doctest failures with pypy

### ISSUE THREAD

**Issue by msabramo** [lericson/pylibmc#132]
I have not looked in depth, but in the past I have seen this when code makes assumptions about the ordering in which Python iterates through a dict, as this seems to be deterministic on CPython <= 2.7 and non-deterministic on CPython >= 3 and PyPy.

```
(py26.venv)marca@marca-mac:~/dev/git-repos/pylibmc$ tox -e pypy
GLOB sdist-make: /Users/marca/dev/git-repos/pylibmc/setup.py
pypy inst-nodeps: /Users/marca/dev/git-repos/pylibmc/.tox/dist/pylibmc-1.3.100-dev.zip
pypy runtests: commands[0]
nose.plugins.pylibmc: INFO: path to dev build: build/lib.macosx-10.8-x86_64-2.7
nose.plugins.pylibmc: INFO: loaded _pylibmc from /Users/marca/dev/git-repos/pylibmc/.tox/pypy/site-packages/_pylibmc.pypy-20.so
nose.plugins.pylibmc: WARNING: double-check the source path
nose.plugins.pylibmc: WARNING: tests are not running on the dev build!
nose.plugins.pylibmc: INFO: testing pylibmc 1.3.100-dev for libmemcached 1.0.16 (compression=True, sasl=True)
Doctest: tests.make_test_client ... ok
Doctest: doctests.txt ... FAIL
testBehaviors (tests.test_client.ClientTests) ... ok
test_cas (tests.test_client.ClientTests) ... ok
test_touch (tests.test_client.ClientTests) ... ok
test_zerokey (tests.test_client.ClientTests) ... ok
Doctest: tests.test_client.make_test_client ... ok
testAppend (tests.test_cmemcached.TestCmemcached) ... ok
testBigGetMulti (tests.test_cmemcached.TestCmemcached) ... ok
testDelete (tests.test_cmemcached.TestCmemcached) ... ok
testFunnyDelete (tests.test_cmemcached.TestCmemcached) ... ok
testGetMulti (tests.test_cmemcached.TestCmemcached) ... ok
testPrepend (tests.test_cmemcached.TestCmemcached) ... ok
testSetAndGet (tests.test_cmemcached.TestCmemcached) ... ok
test_exhaust (tests.test_pooling.ClientPoolTests) ... ok
test_simple (tests.test_pooling.ClientPoolTests) ... ok
tests.test_translate.test_translate ... ok
tests.test_translate.test_udp_translate ... ok
tests.test_translate.test_udp_translate_ipv6 ... ok
tests.test_translate.test_translate_with_weight_string ... ok
tests.test_translate.test_translate_with_weight_kwd ... ok
tests.test_translate.test_udp_translate_ipv6_with_weight ... ok

======================================================================
FAIL: Doctest: doctests.txt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marca/opt/pypy-2.0-beta1/lib-python/2.7/doctest.py", line 2201, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for doctests.txt
  File "/Users/marca/dev/git-repos/pylibmc/tests/doctests.txt", line 0

----------------------------------------------------------------------
File "/Users/marca/dev/git-repos/pylibmc/tests/doctests.txt", line 204, in doctests.txt
Failed example:
    c.incr_multi(('a', 'b', 'c'), delta=1)
Exception raised:
    Traceback (most recent call last):
      File "/Users/marca/opt/pypy-2.0-beta1/lib-python/2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest doctests.txt[76]>", line 1, in <module>
        c.incr_multi(('a', 'b', 'c'), delta=1)
    NotFound: 3 keys not found
----------------------------------------------------------------------
File "/Users/marca/dev/git-repos/pylibmc/tests/doctests.txt", line 205, in doctests.txt
Failed example:
    list(sorted(c.get_multi(('a', 'b', 'c')).items()))
Expected:
    [('a', 2), ('b', 1), ('c', 5)]
Got:
    [('a', 1), ('b', 0), ('c', 4)]
----------------------------------------------------------------------
File "/Users/marca/dev/git-repos/pylibmc/tests/doctests.txt", line 211, in doctests.txt
Failed example:
    c.incr_multi(('a', 'b', 'c'), key_prefix='x', delta=5)
Exception raised:
    Traceback (most recent call last):
      File "/Users/marca/opt/pypy-2.0-beta1/lib-python/2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest doctests.txt[80]>", line 1, in <module>
        c.incr_multi(('a', 'b', 'c'), key_prefix='x', delta=5)
    NotFound: 3 keys not found
----------------------------------------------------------------------
File "/Users/marca/dev/git-repos/pylibmc/tests/doctests.txt", line 212, in doctests.txt
Failed example:
    list(sorted(c.get_multi(('a', 'b', 'c'), key_prefix='x').items()))
Expected:
    [('a', 6), ('b', 5), ('c', 9)]
Got:
    [('a', 1), ('b', 0), ('c', 4)]


----------------------------------------------------------------------
Ran 22 tests in 10.136s

FAILED (failures=1)
ERROR: InvocationError: '/Users/marca/dev/git-repos/pylibmc/bin/runtests.py -v tests --with-doctest'
____________________________________________________________________________________ summary _____________________________________________________________________________________
ERROR:   pypy: commands failed
```

**Comment by andreif** [comment]
Seems working fine now with pypy3.5-6.0.0, see #250.

**Comment by andreif** [comment]
Also tested with `pypy3.5-5.10.1` and `pypy2.7-6.0`.
